### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by ahivapepelui** [nviennot/android-checkin#10]
good morning
what am I doing wrong?
$git clone https://github.com/nviennot/android-checkin
$cd android-checkin/
$new com.android.checkin.Checkin.new(myemail@gmail.com, mypass).checkin()
bash: error sintáctico cerca del elemento inesperado `('

bash error translate
bash: syntax error near unexpected element ' ( '
I have ubuntu 14.04 in Spanish.

**Comment by nviennot** [comment]
you are trying to type some java into bash. you shouldn't do that.
