### ISSUE TITLE
Using android-checkin.jar with a higher SDK

### ISSUE THREAD

**Issue by IzzySoft** [nviennot/android-checkin#7]
Currently, checkin.jar is fixed to SDK 16 (Android 4.1) if I read this correctly. Is it possible creating an AndroidID for a different/higher SDK – and if, how to achieve this (preferably in a way not requiring Java development knowledge)?

**Comment by nviennot** [comment]
at the moment, there is no way to achieve this without a bit of java knowledge.

**Comment by IzzySoft** [comment]
I was afraid so. But I guess you've got that knowledge; couldn't you create a version with, say, SDK 19 (Kitkat – which currently is the most used Android version around) and attach that in the releases area? Guess I'm not the only one who would be very thankful for that :)

**Comment by nviennot** [comment]
change it here: https://github.com/nviennot/android-checkin/blob/master/src/main/java/com/android/checkin/Checkin.java#L181

**Comment by IzzySoft** [comment]
Thanks for the pointer! For those not familiar with Java (like me), could you also add how to create the `.jar` afterwards? Most likely many of us only have JRE installed, but no JDK – not to speak of having _used_ SDK ;)

Easiest way (from the users' POV) would be some config file or command-line parameter to pass for overriding those values – which probably would be demanding too much work from your end. Hence my suggestion of having multiple `.jar` files ready for "major versions", at the moment I'd say SDK 19 (Kitkat), 22 (LP 5.1) and 23 (Marshmallow) should be fine for the next year at least, in addition to the existing JB/4.1 one.

Thanks a lot in advance – whichever way you chose!

**Comment by nviennot** [comment]
I don't remember how to do the .jar. I suck hard at java you see :/

**Comment by IzzySoft** [comment]
Ouch. Then hopefully someone jumps in building the `.jar` files and providing them back to you …

**Comment by IzzySoft** [comment]
OK, problem solved: [DummyDroid](http://www.onyxbits.de/dummydroid) created an android_id using my devices real `build.prop` (can use any `build.prop` and, if you wish, you can also fake/manipulate all specs).
